//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaConquista_WF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetallleFactura
    {
        public int dtfact_Id { get; set; }
        public Nullable<int> fact_Id { get; set; }
        public Nullable<int> produ_IdProducto { get; set; }
        public string defact_DescripcionProducto { get; set; }
        public Nullable<decimal> defact_CantidadProducto { get; set; }
        public Nullable<decimal> defact_PrecioProducto { get; set; }
        public Nullable<decimal> defact_Subtotal { get; set; }
        public Nullable<decimal> defact_Isv { get; set; }
        public Nullable<decimal> defact_Descuento { get; set; }
        public Nullable<decimal> defact_Total { get; set; }
        public Nullable<bool> defact_Estado { get; set; }
        public int UsuarioCrea { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual tbEncabezadoFactura tbEncabezadoFactura { get; set; }
        public virtual tbProducto tbProducto { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
